export const PRODUCTS_CATALOG = [
  {
    id: 'monolith-carryon-35l',
    slug: 'monolith-carryon-35l',
    brand: 'KOKIO',
    category: 'carry-on',
    categoryLabel: 'CARRY-ON LUGGAGE',
    collection: 'monolith',
    collectionLabel: 'THE MONOLITH SERIES',
    tag: 'KOKIO • ONLINE EXCLUSIVE',
    name: 'The Monolith Carry-On 35L',
    story: 'Forged 6061-T6 aerospace aluminum shell with flush TSA zinc latches and whisper-glide bearings.',
    specs: '35L Capacity • 4.2 kg • 18µ Anodized',
    material: 'Aerospace 6061-T6 Aluminum',
    materialType: 'aluminum',
    colors: ['Silver Aluminum', 'Onyx Black', 'Champagne Gold'],
    price: '₹1,09,999',
    rawPrice: 109999,
    image: '/images/kokio_monolith_carryon.jpg',
    gallery: ['/images/kokio_monolith_carryon.jpg', '/images/kokio_monolith_open.jpg', '/images/kokio_monolith_checkin.jpg'],
    highlights: [
      'Aerospace 6061-T6 Aluminum',
      'Dual Flush TSA Zinc Latches',
      'Whisper-Glide Bearing Wheels',
    ],
    details: {
      dimensions: '55 x 40 x 23 cm (Overhead Bin Compliant)',
      volume: '35 Liters',
      weight: '4.2 kg',
      wheels: '360° Ball-Bearing Dual Spinner Wheels',
      locks: 'Dual Flush TSA Combination Zinc Latches',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'apex-titanium-trunk-88l',
    slug: 'apex-titanium-trunk-88l',
    brand: 'KOKIO',
    category: 'trunks',
    categoryLabel: 'EXTENDED TRUNKS',
    collection: 'expedition',
    collectionLabel: 'EXPEDITION SERIES',
    tag: 'KOKIO • SIGNATURE TRUNK',
    name: 'The Apex Titanium Trunk 88L',
    story: 'Full-sized continental trunk with dual-chamber dividers and reinforced titanium corner armor.',
    specs: '88L Capacity • 6.1 kg • Dual TSA Locks',
    material: 'Brushed Titanium Alloy',
    materialType: 'titanium',
    colors: ['Titanium Grey', 'Deep Onyx'],
    price: '₹1,39,999',
    rawPrice: 139999,
    image: '/images/kokio_titanium_trunk.jpg',
    gallery: ['/images/kokio_titanium_trunk.jpg', '/images/kokio_titanium_trunk_side.jpg', '/images/kokio_iceland_trunk.jpg'],
    highlights: [
      'Brushed Titanium Alloy Frame',
      'Dual-Chamber Zip Dividers',
      'Reinforced Corner Shields',
    ],
    details: {
      dimensions: '73 x 43 x 37.5 cm (Deep Trunk Architecture)',
      volume: '88 Liters',
      weight: '6.1 kg',
      wheels: 'Whisper-Glide Bearing Wheels',
      locks: 'Integrated TSA Combination Latches',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'horizon-leather-weekender',
    slug: 'horizon-leather-weekender',
    brand: 'KOKIO',
    category: 'bags',
    categoryLabel: 'BAGS & DUFFELS',
    collection: 'atelier',
    collectionLabel: 'ATELIER BESPOKE',
    tag: 'KOKIO • ATELIER BESPOKE',
    name: 'The Horizon Leather Weekender',
    story: 'Hand-stitched full-grain Italian leather duffel with brass hardware and organic patina.',
    specs: '45L Capacity • Tuscan Vachetta • Waxed Thread',
    material: 'Tuscan Full-Grain Leather',
    materialType: 'leather',
    colors: ['Chestnut Brown', 'Espresso Black'],
    price: '₹79,999',
    rawPrice: 79999,
    image: '/images/kokio_leather_weekender.jpg',
    gallery: ['/images/kokio_leather_weekender.jpg', '/images/kokio_leather_weekender_open.jpg', '/images/kokio_passport_folio.jpg'],
    highlights: [
      '100% Tuscan Full-Grain Leather',
      'Hand Saddle-Stitching',
      'Solid Brass Hardware',
    ],
    details: {
      dimensions: '52 x 28 x 26 cm',
      volume: '45 Liters',
      weight: '2.4 kg',
      strap: 'Removable Padded Vachetta Leather Shoulder Strap',
      lining: 'Water-Resistant Cotton Canvas Lining',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'iceland-subzero-trunk',
    slug: 'iceland-subzero-trunk',
    brand: 'KOKIO',
    category: 'trunks',
    categoryLabel: 'EXTENDED TRUNKS',
    collection: 'expedition',
    collectionLabel: 'EXPEDITION SERIES',
    tag: 'KOKIO • LIMITED EDITION',
    name: 'Iceland Sub-Zero Trunk 110L',
    story: 'Architectural trunk engineered to withstand -40°C sub-zero environments and high-impact drops.',
    specs: '110L Capacity • Sub-Zero Rubber Seal • Serial Stamped',
    material: 'Aerospace 6061-T6 Aluminum',
    materialType: 'aluminum',
    colors: ['Arctic White', 'Tactical Slate'],
    price: '₹1,89,999',
    rawPrice: 189999,
    image: '/images/kokio_iceland_trunk.jpg',
    gallery: ['/images/kokio_iceland_trunk.jpg', '/images/kokio_titanium_trunk.jpg', '/images/kokio_titanium_trunk_side.jpg'],
    highlights: [
      'Tested at -40°C Sub-Zero',
      'Hermetic Hydro-Seal Gasket',
      'Laser Stamped Serial Number',
    ],
    details: {
      dimensions: '78 x 46 x 40 cm',
      volume: '110 Liters',
      weight: '6.8 kg',
      gasket: 'Sub-Zero Rubber Hydro-Seal',
      serial: 'Laser Serial Number Stamped',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'florentine-executive-briefcase',
    slug: 'florentine-executive-briefcase',
    brand: 'KOKIO',
    category: 'bags',
    categoryLabel: 'BAGS & DUFFELS',
    collection: 'metropolitan',
    collectionLabel: 'METROPOLITAN LINE',
    tag: 'KOKIO • METROPOLITAN LINE',
    name: 'Florentine Executive Briefcase',
    story: 'Slim executive briefcase with padded laptop core and brass TSA combination lock.',
    specs: '16L Capacity • Tuscan Leather • Laptop Core',
    material: 'Tuscan Vachetta Leather',
    materialType: 'leather',
    colors: ['Cognac Tan', 'Noir Black'],
    price: '₹49,999',
    rawPrice: 49999,
    image: '/images/kokio_executive_briefcase.jpg',
    gallery: ['/images/kokio_executive_briefcase.jpg', '/images/kokio_crossbody_sling.jpg', '/images/kokio_passport_folio.jpg'],
    highlights: [
      'Water-Resistant Tuscan Leather',
      'TSA Laptop Protective Core (up to 16")',
      'Solid Brass Lock',
    ],
    details: {
      dimensions: '40 x 30 x 9 cm',
      volume: '16 Liters',
      weight: '1.6 kg',
      laptop: 'Fits up to 16" MacBook Pro',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'monolith-checkin-68l',
    slug: 'monolith-checkin-68l',
    brand: 'KOKIO',
    category: 'trunks',
    categoryLabel: 'EXTENDED TRUNKS',
    collection: 'monolith',
    collectionLabel: 'THE MONOLITH SERIES',
    tag: 'KOKIO • ICONIC ARCHITECTURE',
    name: 'The Monolith Check-In 68L',
    story: 'Medium check-in luggage forged with 5-axis CNC chassis and soundproof interior lining.',
    specs: '68L Capacity • 5.1 kg • Soundproof Interior',
    material: 'Aerospace 6061-T6 Aluminum',
    materialType: 'aluminum',
    colors: ['Silver Aluminum', 'Onyx Black'],
    price: '₹1,24,999',
    rawPrice: 124999,
    image: '/images/kokio_monolith_checkin.jpg',
    gallery: ['/images/kokio_monolith_checkin.jpg', '/images/kokio_monolith_carryon.jpg', '/images/kokio_monolith_open.jpg'],
    highlights: [
      'Unibody CNC Aluminum Shell',
      'Soundproof Jacquard Lining',
      '360° Ball Bearing Wheels',
    ],
    details: {
      dimensions: '66 x 44 x 26.5 cm',
      volume: '68 Liters',
      weight: '5.1 kg',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'florentine-crossbody-sling',
    slug: 'florentine-crossbody-sling',
    brand: 'KOKIO',
    category: 'accessories',
    categoryLabel: 'TRAVEL ACCESSORIES',
    collection: 'metropolitan',
    collectionLabel: 'METROPOLITAN LINE',
    tag: 'KOKIO • METROPOLITAN LINE',
    name: 'Florentine Crossbody Sling',
    story: 'Compact Italian vachetta leather sling bag designed for quick airport transit & essentials.',
    specs: '6L Capacity • Italian Leather • Brass Hardware',
    material: 'Tuscan Vachetta Leather',
    materialType: 'leather',
    colors: ['Chestnut Brown', 'Noir Black'],
    price: '₹34,999',
    rawPrice: 34999,
    image: '/images/kokio_crossbody_sling.jpg',
    gallery: ['/images/kokio_crossbody_sling.jpg', '/images/kokio_passport_folio.jpg', '/images/kokio_executive_briefcase.jpg'],
    highlights: [
      'Hand-Selected Vachetta Leather',
      'Quick-Access Passport Pocket',
      'Adjustable Shoulder Strap',
    ],
    details: {
      dimensions: '26 x 16 x 7 cm',
      volume: '6 Liters',
      weight: '0.6 kg',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'tuscan-passport-folio',
    slug: 'tuscan-passport-folio',
    brand: 'KOKIO',
    category: 'accessories',
    categoryLabel: 'TRAVEL ACCESSORIES',
    collection: 'atelier',
    collectionLabel: 'ATELIER BESPOKE',
    tag: 'KOKIO • ATELIER BESPOKE',
    name: 'Tuscan Leather Passport Folio',
    story: 'Full-grain Tuscan vachetta leather passport holder with RFID protection and card slots.',
    specs: 'RFID Shield • Dual Passport Slots • Pen Holder',
    material: 'Tuscan Full-Grain Leather',
    materialType: 'leather',
    colors: ['Cognac Tan', 'Heritage Brown'],
    price: '₹19,999',
    rawPrice: 19999,
    image: '/images/kokio_passport_folio.jpg',
    gallery: ['/images/kokio_passport_folio.jpg', '/images/kokio_leather_weekender.jpg', '/images/kokio_crossbody_sling.jpg'],
    highlights: [
      'RFID Blocking Metal Layer',
      'Holds 2 Passports + 6 Cards',
      'Monogramming Included',
    ],
    details: {
      dimensions: '14.5 x 11 x 1.5 cm',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'expedition-tourist-pack',
    slug: 'expedition-tourist-pack',
    brand: 'KOKIO',
    category: 'bags',
    categoryLabel: 'BAGS & DUFFELS',
    collection: 'expedition',
    collectionLabel: 'EXPEDITION SERIES',
    tag: 'KOKIO • EXPEDITION SERIES',
    name: 'Expedition Tourist Pack',
    story: 'Modular ballistic nylon and vachetta leather travel backpack with trolley sleeve.',
    specs: '28L Capacity • Trolley Sleeve • Waterproof Zippers',
    material: 'Ballistic Nylon & Vachetta',
    materialType: 'nylon',
    colors: ['Onyx Black', 'Titanium Grey'],
    price: '₹64,999',
    rawPrice: 64999,
    image: '/images/kokio_tourist_pack.jpg',
    gallery: ['/images/kokio_tourist_pack.jpg', '/images/kokio_crossbody_sling.jpg', '/images/kokio_iceland_trunk.jpg'],
    highlights: [
      '1680D Ballistic Nylon Construction',
      'Integrated Luggage Pass-Through',
      'Ergonomic Padded Harness',
    ],
    details: {
      dimensions: '45 x 31 x 18 cm',
      volume: '28 Liters',
      weight: '1.4 kg',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'kokio-academia-college-bag',
    slug: 'kokio-academia-college-bag',
    brand: 'KOKIO',
    category: 'bags',
    categoryLabel: 'BAGS & DUFFELS',
    collection: 'atelier',
    collectionLabel: 'ATELIER BESPOKE',
    tag: 'KOKIO • ACADEMIA EDITION',
    name: 'The Academia Leather College Satchel',
    story: 'Bespoke full-grain Tuscan leather messenger and college bag with padded 16" laptop sleeve, dual brass buckle latches, and student organizer folio.',
    specs: '22L Capacity • 16" Laptop Core • Tuscan Vachetta',
    material: 'Tuscan Full-Grain Leather',
    materialType: 'leather',
    colors: ['Chestnut Brown', 'Espresso Black', 'Cognac Tan'],
    price: '₹42,999',
    rawPrice: 42999,
    image: '/images/kokio_college_bag.jpg',
    gallery: ['/images/kokio_college_bag.jpg', '/images/kokio_leather_weekender.jpg', '/images/kokio_passport_folio.jpg'],
    highlights: [
      'Handcrafted Tuscan Full-Grain Leather',
      'Dedicated 16" MacBook Pro Sleeve',
      'Twin Front Quick-Access Notebook Pouches',
    ],
    details: {
      dimensions: '42 x 31 x 12 cm',
      volume: '22 Liters',
      weight: '1.5 kg',
      laptop: 'Fits up to 16" MacBook Pro',
      strap: 'Adjustable Padded Vachetta Shoulder Strap',
      warranty: 'Kokio Global Care',
    },
  },
  {
    id: 'kokio-scholar-school-backpack',
    slug: 'kokio-scholar-school-backpack',
    brand: 'KOKIO',
    category: 'bags',
    categoryLabel: 'BAGS & DUFFELS',
    collection: 'metropolitan',
    collectionLabel: 'METROPOLITAN LINE',
    tag: 'KOKIO • SCHOLAR EDITION',
    name: 'The Scholar Technical School Backpack',
    story: 'Heavy-duty ballistic nylon student backpack with ergonomic air-mesh harness, modular textbook divider, and waterproof zip pockets.',
    specs: '26L Capacity • Ergonomic Harness • Ballistic Nylon',
    material: 'Ballistic Nylon & Vachetta',
    materialType: 'nylon',
    colors: ['Onyx Black', 'Titanium Grey'],
    price: '₹36,999',
    rawPrice: 36999,
    image: '/images/kokio_school_backpack.jpg',
    gallery: ['/images/kokio_school_backpack.jpg', '/images/kokio_tourist_pack.jpg', '/images/kokio_crossbody_sling.jpg'],
    highlights: [
      '1680D Water-Resistant Ballistic Nylon',
      'Orthopedic Lumbar & Ergonomic Shoulder Straps',
      'Dual Multi-Tier Textbook & Tablet Dividers',
    ],
    details: {
      dimensions: '44 x 30 x 16 cm',
      volume: '26 Liters',
      weight: '1.2 kg',
      harness: 'Breathable Honeycomb Air-Mesh Harness',
      compartments: '3 Main Chambers + Padded Tech Sleeve',
      warranty: 'Kokio Global Care',
    },
  },
];

export const CATEGORY_METADATA = {
  all: {
    slug: 'all',
    label: 'COMPLETE TAXONOMY',
    title: 'All Instruments',
    subtitle: 'A considered selection of aerospace aluminum trunks, Tuscan leather weekenders, college satchels, school backpacks, and accessories.',
    intro: 'Explore museum-grade luggage, travel bags, and metrology instruments engineered to accompany extraordinary journeys across 100,000 miles.',
  },
  luggage: {
    slug: 'luggage',
    label: 'AEROSPACE ARCHITECTURE',
    title: 'Luggage Collection',
    subtitle: 'Precision-engineered aerospace aluminum carry-on, check-in, and extended continental trunks.',
    intro: 'Aerospace 6061-T6 aluminum trunks forged under hydraulic pressure with flush TSA zinc latches and whisper-glide bearings.',
  },
  'carry-on': {
    slug: 'carry-on',
    label: 'OVERHEAD BIN SPECIFICATION',
    title: 'Cabin & Carry-On',
    subtitle: 'Aerospace aluminum carry-on trunks engineered for international overhead bins.',
    intro: 'Precision-engineered companions for journeys that move quickly without compromising structural integrity.',
  },
  cabin: {
    slug: 'cabin',
    label: 'OVERHEAD BIN SPECIFICATION',
    title: 'Cabin Carry-On',
    subtitle: 'Aerospace aluminum carry-on trunks engineered for international overhead bins.',
    intro: 'Precision-engineered companions for journeys that move quickly without compromising structural integrity.',
  },
  trunks: {
    slug: 'trunks',
    label: 'CONTINENTAL VOLUME',
    title: 'Extended Trunks',
    subtitle: 'Deep-capacity aluminum and titanium trunks built for multi-week continental journeys.',
    intro: 'Deep continental trunks designed to safeguard multi-week wardrobes against extreme carousel shock and transit conditions.',
  },
  checkin: {
    slug: 'checkin',
    label: 'CONTINENTAL VOLUME',
    title: 'Check-In Luggage',
    subtitle: 'Medium volume travel trunks with 5-axis CNC chassis and soundproof lining.',
    intro: 'Balanced volume check-in trunks engineered with unibody shell precision for global voyages.',
  },
  bags: {
    slug: 'bags',
    label: 'TUSCAN VACHETTA & BALLISTIC CRAFT',
    title: 'Bags & Backpacks',
    subtitle: 'Full-grain Tuscan leather weekenders, college satchels, school backpacks, and executive briefcases.',
    intro: 'Handcrafted leather college satchels, ergonomic student backpacks, and weekenders engineered to accompany daily study, business pursuits, and global departures.',
  },
  duffels: {
    slug: 'duffels',
    label: 'TUSCAN VACHETTA CRAFT',
    title: 'Leather Duffels',
    subtitle: 'Full-grain Italian leather weekender bags with carbon-reinforced handles.',
    intro: 'Tactile richness and organic vegetable-tanned leather crafted for short departures and weekend travel.',
  },
  accessories: {
    slug: 'accessories',
    label: 'BESPOKE DETAILS',
    title: 'Travel Accessories',
    subtitle: 'Passport folios, leather luggage tags, and modular packing organizers.',
    intro: 'Essential travel folios, RFID passport holders, and bespoke leather accessories hand-finished with brass accents.',
  },
  monolith: {
    slug: 'monolith',
    label: 'AEROSPACE 6061-T6',
    title: 'The Monolith Series',
    subtitle: 'Technical unibody aluminum luggage with flush TSA zinc latches.',
    intro: 'Our flagship creation, engineered with aerospace-grade aluminum and metrology precision for a lifetime of movement.',
  },
  metropolitan: {
    slug: 'metropolitan',
    label: 'URBAN EXECUTIVE',
    title: 'Metropolitan Line',
    subtitle: 'Executive leather briefcases, slings, and urban commuter gear.',
    intro: 'Refined urban travel tools crafted with water-resistant Tuscan leather and padded laptop protection.',
  },
  expedition: {
    slug: 'expedition',
    label: 'SUB-ZERO SPECIFICATION',
    title: 'Expedition Series',
    subtitle: 'Extreme weather trunks with hermetic hydro-seal gaskets and titanium armor.',
    intro: 'Architectural travel trunks engineered for polar solitude, arctic fjords, and rugged continental exploration.',
  },
  atelier: {
    slug: 'atelier',
    label: 'HAND-FINISHED MASTERPIECES',
    title: 'Atelier Bespoke',
    subtitle: 'Hand-stitched Tuscan vachetta leather goods and limited edition pieces.',
    intro: 'Artisanal creations tanned in organic chestnut extracts, hand-stitched with waxed linen thread.',
  },
};
